
[[server]]
name = "kaspa-ng.org"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://eu-1.kaspa-ng.org/mainnet"

[[server]]
name = "kaspa-ng.org"
location = "EU"
protocol = "borsh"
network = "testnet-10"
address = "wss://eu-1.kaspa-ng.org/testnet-10"

[[server]]
name = "kaspa-ng.org"
location = "EU"
protocol = "borsh"
network = "testnet-11"
address = "wss://eu-1.kaspa-ng.org/testnet-11"

[[server]]
name = "kaspa-ng.org"
location = "US"
protocol = "borsh"
network = "mainnet"
address = "wss://us-west-1.kaspa-ng.org/mainnet"

[[server]]
name = "kaspa-ng.org"
location = "US"
protocol = "borsh"
network = "testnet-10"
address = "wss://us-west-1.kaspa-ng.org/testnet-10"

[[server]]
name = "kaspa-ng.org"
location = "US"
protocol = "borsh"
network = "testnet-11"
address = "wss://us-west-1.kaspa-ng.org/testnet-11"

[[server]]
name = "kaspa-ng.io"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://eu-1.kaspa-ng.io:443/mainnet"

[[server]]
name = "kaspa-ng.io"
location = "EU"
protocol = "borsh"
network = "testnet-10"
address = "wss://eu-1.kaspa-ng.io:443/testnet-10"

[[server]]
name = "kaspa-ng.io"
location = "EU"
protocol = "borsh"
network = "testnet-11"
address = "wss://eu-1.kaspa-ng.io:443/testnet-11"
